# Deployment e Service para Go + React no k3s (Raspberry Pi - ARM64)
# Este arquivo considera que as imagens Docker foram buildadas para ARM64
# Exemplo de tag: meuusuario/go-backend:arm64 e meuusuario/react-frontend:arm64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name: go-backend
          image: aperissinotto/go-backend:19574439845
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: go-backend-service
spec:
  selector:
    app: go-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: aperissinotto/react-frontend:19574439845
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: VITE_API_URL
              value: "http://10.43.22.100:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 8181
      targetPort: 3000
      protocol: TCP